import Footer from "@/components/layout/footer/footer";
import Header from "@/components/layout/header/header";
import type { Metadata } from "next";
import { Barlow_Condensed, DM_Sans, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-gt-american",
  subsets: ["latin"],
  weight: ["700"],
  display: "swap",
});

const dmSans = DM_Sans({
  variable: "--font-favorit",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <html
        lang="en"
        className={`${inter.variable} ${barlowCondensed.variable} ${dmSans.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col ">{children}</body>
      </html>
      <Footer />
    </>
  );
}
